# Generated by Django 5.2.15 on 2026-06-25 19:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('user_id', models.CharField(max_length=255)),
                ('merchant_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('memo', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('AUTO_APPROVE', 'Auto Approve'), ('NEEDS_REVIEW', 'Needs Review'), ('AUTO_BLOCK', 'Auto Block')], max_length=20)),
                ('risk_score', models.IntegerField(default=0)),
                ('reasons', models.JSONField(default=list)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction')),
            ],
        ),
    ]
