# Generated by Django 5.2.15 on 2026-06-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='enrichment_queued',
            field=models.BooleanField(default=False),
        ),
    ]
