# Generated by Django 5.2.15 on 2026-06-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_add_enrichment_queued_to_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='request_id',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
    ]
